#define WIDTH 1024
#define HEIGHT 768

#define PIXEL_SIZE 4

#define PIXEL_WIDTH (WIDTH / PIXEL_SIZE)
#define PIXEL_HEIGHT (HEIGHT / PIXEL_SIZE)

#define PIXEL_SPRAY_RANGE 32
#define PIXEL_ERASER_SIZE 9
#define PIXEL_BRUSH_LARGE 7

#define PIXEL_SPRAY_MULTIPLIER 4
